version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: Europe/Zagreb
    open-pull-requests-limit: 5
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
      production-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '@nestjs/*'
        update-types:
          - version-update:semver-major
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: Europe/Zagreb
    groups:
      github-actions:
        patterns:
          - '*'
